name: tests

on: [push]

env:
  DUCKDB_FILENAME: parquet_example
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Install dependencies
        run: uv sync --group dev
      - name: Run fileserver
        run: uv run --directory tests/ fileserver.py &
      - name: Run mcp server
        run: uv run fastmcp run -t http app/main.py &
      - run: sleep 5
      - name: Run tests
        run: uv run --directory tests/ pytest e2e_tests.py
  inspector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Run mcp server
        run: uv run fastmcp run -t http app/main.py &
      - name: Run inspector
        run: npx @modelcontextprotocol/inspector --cli \ http://localhost:8000/mcp --method tools/list

