name: tests

on: [push]

env:
  DUCKDB_FILENAME: tests/parquet_example
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  OPIK_API_KEY: ${{ secrets.OPIK_API_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/mcp-composite-action
        with:
          DUCKDB_FILENAME: 'tests/parquet_example'
      - name: Run tests
        run: uv run --directory tests/ pytest e2e_tests.py
  inspector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: ./.github/workflows/mcp-composite-action
        with:
          DUCKDB_FILENAME: 'tests/parquet_example'
      - name: Run inspector
        run: npx @modelcontextprotocol/inspector --cli http://127.0.0.1:8000/mcp --method tools/list
  opik:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Run opik experiments
        run: uv run tests/opik/tool_calls.py
